#!/bin/bash
echo "The school is open!"
[master 95a0fc8] echo "The school is open!"
 5 files changed, 4 insertions(+)
 create mode 100644 0x01-git/bash/alx
 create mode 100644 0x01-git/bash/school
 create mode 100644 0x01-git/c/c_is_fun.c
 create mode 100644 0x01-git/js/index.js
 create mode 100644 0x01-git/js/main.js
